### PR TITLE
more controls, restructure etc

### PR DESCRIPTION
**Pull request by yaneq**

### CODE REVIEW

**Comment by christofdamian** [comment]
maybe?

**Comment by jhmarina** [comment]
:+1:

**Comment by ivandelrio** [comment]
+1

**Comment by yaneq** [comment]
@christofdamian maybe what?

**Comment by christofdamian** [comment]
I have no idea if I can plus one this :-)

**Comment by yaneq** [comment]
you can ;-)

**Comment by dsager** [comment]
+1 :see_no_evil: 
see, @christofdamian, it's easy ;)

**Pull request merged**
